name: Generate README
on: workflow_dispatch

permissions:
  contents: write

# Python and rustup are pre-installed

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up readmeai
        run: pip install readmeai

      - name: Generate readme
        run: |
          readmeai --repository $REPOSITORY \
          --output README.md \
          --header-style compact \
          --image black \
          --toc-style bullet
        env:
          REPOSITORY: "https://github.com/${{ github.repository }}"

      - name: Commit and push readme
        run: |
          git config --global user.name 'Finn Buhse'
          git config --global user.email 'finn.buhse@fdbhealth.com'
          git add README.md
          git commit -m "Overwrote readme with AI-generated readme"
          git push
        
